name: second_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  objectbox: ^4.1.0
  objectbox_flutter_libs: any
  path_provider: ^2.1.5
  cupertino_icons: ^1.0.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.0.0
  objectbox_generator: any
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1


flutter:
  uses-material-design: true
